version: "3.2"

services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /usr/src
    depends_on:
      - postgresql
    ports:
      - "8000:8000"
    environment:
      DB_PASSWORD: sup3rs3cr3t
      DB_USER: sup3rus3r
      DB_NAME: django
      DB_PORT: 5432
      DB_HOST: postgresql
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sup3rs3cr3t
      POSTGRES_USER: sup3rus3r
      POSTGRES_DB: django
